### ISSUE TITLE
Dependencies Oxide-bla-bla di branch dev

### ISSUE THREAD

**Issue by Ackyras** [ranggons/lms-frontend#7]
Error cok @ikhbaaalll

**Comment by Ackyras** [comment]
kasih insight sob

**Comment by Ackyras** [comment]
msi sama sob, blom bisa 

![image](https://user-images.githubusercontent.com/45270846/220741593-e29a2bb4-8aa9-49c5-8b4b-d4ef2fd6e3fa.png)

**Comment by ikhbaaalll** [comment]
npm install --legacy-peer-deps
